### ISSUE TITLE
Error in get_bytes()

### ISSUE THREAD

**Issue by jeremy-skippen** [gtaylor/winrandom-ctypes#3]
Your `get_bytes()` function returns the wrong attribute of the string buffer

    return s.value

should be

    return s.raw

`s.value` returns the buffer as a NUL-terminated string, so for instance:

    b = get_bytes(102400)
    assert len(b) == 102400

will pretty much always fail.

**Comment by gtaylor** [comment]
I'm not currently maintaining this, but send a PR and I'll merge it.
